# Generated by Django 5.2.7 on 2025-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('features', models.TextField(help_text='Enter features separated by commas')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={},
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='service_interest',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
